baseURL = 'https://nettan.b2l.se/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'KalleAnka'
  metaDescription = "hoppar hela dagen"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[taxonomies]
  category= "theme"
  scene = "scenes"
